
POST http://localhost:3000/api/users/register
Content-Type: application/json

 {
    "username": "tuice@hotmail.com",
    "password": "21821112"   
}


###


POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "juice@hotmail.com",
    "password": "21821112"   
}

###
POST http://localhost:3000/api/post/send
Content-Type: application/json

{
    "title": "I väntan på Juni",
    "content": "Dagar Flyter på som vanligt i samma takt?"   
}


###
 
 GET http://localhost:3000/api/post/all


###

 GET http://localhost:3000/api/post/public

###
 GET http://localhost:3000/api/post/63fdd40fa29e21408e0f65f2
