
POST http://localhost:3000/api/users/register
Content-Type: application/json

 {
    "username": "tuice@hotmail.com",
    "password": "21821112"   
}


###


POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "juice@hotmail.com",
    "password": "21821112"   
}

###
POST http://localhost:3000/api/post/send
Content-Type: application/json

{
    "user":"juice",
    "title": "wdadaw",
    "content": "Dagar Flyter på som vanligt i samma takt?"   
}


###
 
 GET http://localhost:3000/api/post/all


###

 GET http://localhost:3000/api/post/public

###
 POST http://localhost:3000/api/post/search
Content-Type: application/json

{
    "user":"juice"
}

###
DELETE http://localhost:3000/api/post/delete
Content-Type: application/json

{
    "user":"tomas",
    "_id":"6401c85c5d56be6eec84be68"
}


###
PUT http://localhost:3000/api/post/like
Content-Type: application/json

{
    "user":"koka",
    "_id":"6401c9225d56be6eec84bf03"
}