
POST http://localhost:3000/api/users/register
Content-Type: application/json

 {
    "username": "casper@hotmail.com",
    "password": "21821112"   
}


###


POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "casper@hotmail.com",
    "password": "21821112"   
}